export const SET_FORMDATA = "SET_FORMDATA"

export const RESET_FORMDATA = "RESET_FORMDATA"

export const GET_DOCTOR_LIST = "GET_DOCTOR_LIST"

export const GET_REFERRAL_DOCTORS = "GET_REFERRAL_DOCTORS"

export const GET_SELECTED_TESTS = "GET_SELECTED_TESTS"

export const REF_TOKEN = "REF_TOKEN"
export const DTRF_TOKEN = "DTRF_TOKEN"

export const SEND_BY = "SEND_BY"

export const GET_USG_FILE = "GET_USG_FILE"

export const DYNAMIC_PATIENT_DETAILS = "DYNAMIC_PATIENT_DETAILS"

export const GET_PATIENT_CONSENT_FILE = "GET_PATIENT_CONSENT_FILE"

export const GET_OTHER_FILES = "GET_OTHER_FILES"

export const GET_DOCTOR_ATTESTATION = "GET_DOCTOR_ATTESTATION"

export const GET_PATIENT_DECLARATION_PNDT = "GET_PATIENT_DECLARATION_PNDT"

export const GET_PATIENT_INFORMED_CONSENT = "GET_PATIENT_INFORMED_CONSENT"

export const GET_CONSENT_INDEMNITY = "GET_CONSENT_INDEMNITY"

export const GET_LIMITATION_OF_TEST = "GET_LIMITATION_OF_TEST"

export const GET_PATIENT_PRIVACY = "GET_PATIENT_PRIVACY"

export const GET_PCPNDT_FILES = "GET_PCPNDT_FILES"

export const GET_REFERRAL_LETTER = "GET_REFERRAL_LETTER"

export const GET_PNS_REPORT = "GET_PNS_REPORT"

export const GET_NTSCAN = "GET_NTSCAN"

export const GET_CBC = "GET_CBC"

export const GET_CBC_DOC = "GET_CBC_DOC"

export const GET_BTH = "GET_BTH"

export const HES = "HES"

export const HPS = "HPS"

export const HDS = "HDS"

export const AUTHENTICATE = "AUTHENTICATE"
export const ROLES = "ROLES"
export const GET_FILES = "GET_FILES"
export const GET_FILES_TO_UPLOAD = "GET_FILES_TO_UPLOAD"
export const GET_FILES_REFERENCE = "GET_FILES_REFERENCE"
export const DELETE_FILE = "DELETE_FILE"
export const CLEAR_DELETE_FILE = "CLEAR_DELETE_FILE"
export const SENT_TO_BDM = "SENT_TO_BDM"
export const IS_COMPLETE = "IS_COMPLETE"
export const SET_FILEUPLOAD = "SET_FILEUPLOAD"
export const GET_MANDATORY_FILES = "GET_MANDATORY_FILES"
